// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dosqlfdqsgcvogxpndrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvc3FsZmRxc2djdm9neHBuZHJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3MzUyNjcsImV4cCI6MjA1NTMxMTI2N30.W6P0TEakPDlKaiXvn-_8IunaU3_IcMOiySrRw3LniAk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);